---
title: "Homework 7"
author: "Raymond Looney"
date: "2/28/2018"
output: html_document
---

##Function to create data
```{r}
dataCreate <- function(mean1=208.3, mean2=302.4, mean3=67.8, mean4=89.22,
                       n1=200,n2=200,n3=200,n4=200,
                       sd1=30,sd2=35,sd3=33,sd4=30){
  mydf <- data.frame(control=rnorm(mean = mean1, n=n1, sd=sd1),
                     test=rnorm(mean=mean2, n=n2, sd=sd2),
                     thing1=rnorm(mean=mean3, n=n3, sd=sd3),
                     thing2=rnorm(mean=mean4, n=n4, sd=sd4))
  return(mydf)
}
myDF <-dataCreate(mean1=100.59)
head(myDF)
```

##Function for ANOVA
```{r}
library(reshape2)

myDF2 <- melt(myDF) 
ANOVA <- function(data=myDF2){
  myANOVA <- aov(value~variable, data=data)
  summary(myANOVA)
}
ANOVA(data=myDF2)
ANOVA()
myANOVA <- aov(value~variable, data=myDF2)
summary(myANOVA)

```

##Function to create box plot
```{r}
library(ggplot2)
library(ggplot2)
ANOVAPlot <- function(data=myDF2){
  ggplot(data=data,aes(x=variable, y=value, fill=variable)) + geom_boxplot()
}
ANOVAPlot()

```

## Running ANOVA with different mean values
```{r}
df5 <- dataCreate(mean1=375.5, mean2=375.5)
df5<-melt(df5)
ANOVA(data=df5)
ANOVAPlot(df5)
```


